version: '3.9.6'

services:
 

  vsn-cont1:
    image: $DOCKER_REGISTRY/vsn_next_word:latest
    pull_policy: if_not_present
    
    working_dir: /vsn_nw
    ports:
    - 7000:8000
    volumes:
    - .:/vsn_nw
    # docker run --name <container_name> <path on local system>:<location of container data> <image_name>



  vsn-cont2:
    # Build an image first from source code
    # build:
    # context: .
    # Name the image as bellow 
    image: $DOCKER_REGISTRY/vsn_next_word:latest
    pull_policy: if_not_present
  # Use this port mapping

    working_dir: /vsn_nw

    ports:
    - 8000:8000
  # 
    volumes:
    - .:/vsn_nw