version: '3.9.6'

services:
 # Name of Container 
 vsnai-test-cont:
  # Build an image first from source code
  # build:
  #  # Build in current directory
  #  context: .
  # Name the image as bellow 
  image: gs-vsnai
  # Use this port mapping

  working_dir: /src

  ports:
  - 8000:8000
  # 
  volumes:
  - .:/src